apiVersion: apps/v1

kind: Deployment

metadata: 
  name: microservice-1
  namespace: dev

spec:
  minReadySeconds: 180 
  replicas: 1
  selector: 
    matchLabels: 
     app: microservice-1
  template:  
    metadata:
     labels:
       app: microservice-1
       env: dev
    spec: 
      containers: 
       - name: microservice-1
         image: microservice-1:2.0
         imagePullPolicy: Never
         resources: 
          requests:
             cpu: 0.2
             memory: 100Mi
         readinessProbe:
          httpGet:
            port: 8081
            path: /actuator/health/readiness
          initialDelaySeconds: 120 
          timeoutSeconds: 60
         livenessProbe:
          httpGet:
            port: 8081
            path: /actuator/health/liveness
          initialDelaySeconds: 120
          timeoutSeconds: 60
         env: 
         - name: CUSTOM_MESSAGE
           valueFrom:
             configMapKeyRef:
               name: microservice-1-config-map
               key: custom.message
         envFrom:
         - configMapRef:
             name: microservice-1-config-map-global                
