apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector: 
    matchLabels: 
     app: {{ .Values.app.name }}
     env: {{ .Values.app.namespace }}
  template:  
    metadata:
     labels:
       app: {{ .Values.app.name }}
       env: {{ .Values.app.namespace }}
    spec: 
      containers: 
       - name: {{ .Values.app.name }}
         image: {{ .Values.app.name }}:{{ .Values.app.container.image.version }}
         imagePullPolicy: {{ .Values.app.container.image.pullPolicy }}
         ports:
            - containerPort: 8081
      serviceAccountName: {{ .Values.app.container.serviceAccount }}
      
