apiVersion: apps/v1

kind: Deployment

metadata: 
  name: microservice-1
  namespace: anand

spec:
  minReadySeconds: 180 
  
  replicas: 1
  
  selector: 
    matchLabels: 
     app: microservice-1
  
  template: 
    
    metadata:
     labels:
        app: microservice-1
        env: development
    
    spec: 
      containers: 
       - name: microservice-1
         image: microservice-1:2.0
         imagePullPolicy: Never
         
         readinessProbe:
          httpGet:
            port: 8081
            path: /actuator/health/readiness
          initialDelaySeconds: 120 
          timeoutSeconds: 60
         
         livenessProbe:
          httpGet:
            port: 8081
            path: /actuator/health/liveness
          initialDelaySeconds: 120
          timeoutSeconds: 60
         
         resources:   # hint to the scheduler by the developer how much memory and cpu this pod will take
           requests:  # it helps the scheduler to take decision before scheduling the pod 
             memory: 500Mi
             cpu: 100m
           limits:
             memory: 700Mi
           # native feature of linux - cgroups 
           # limits uses this feature  
           
         
         env: 
         - name: CUSTOM_MESSAGE
           valueFrom:
             configMapKeyRef:
               name: microservice-1-config-map
               key: custom.message
                
         envFrom:
         - configMapRef:
             name: microservice-1-config-map-global                