apiVersion: v1
kind: Service
metadata: 
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  type: ClusterIP        
  ports:
    - name: http
      port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
  selector:
     app: {{ .Values.app.name }}
     env: {{ .Values.app.namespace }}

  
  
