apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: microservice-1
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: microservice-1
  maxReplicas: 3
  minReplicas: 1
  metrics:
   - type: Resource
     resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 150
   - type: Resource
     resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 400Mi

  