# This defines which pod is going to be represented by this service
# The service becomes a network endpoint for other services or external systems ( browser, curl, http clients ) 

apiVersion: v1
kind: Service
metadata: 
  name: microservice-1
spec:
  type: ClusterIP        
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  selector:
     app: microservice-1

  
  
